name: The Life Unlimited Project
favicon: null
layout_spectrum: 0.50452
typography_spectrum: 0.52859
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#b3a38c'
    - '#383127'
    - '#938169'
    - '#5c6971'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
