name: The Life Unlimited Project
favicon: null
layout_spectrum: 0.33376585808582604
typography_spectrum: 0.7262632600031793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9931427608244121
  lightness: 0.7317582953255624
  saturation: 0.5535774331074208
  rhythmicContrast: 0.6545836641453207
purpose: []
