name: The Life Unlimited Project
favicon: null
layout_spectrum: 0.46744
typography_spectrum: 0.51208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d9d3'
    - '#a69f8f'
    - '#5e5f5d'
    - '#7c827b'
    - '#332f2f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
