name: The Life Unlimited Project
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52859
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4efeb'
    - '#c9babf'
    - '#3c3034'
    - '#6d6888'
    - '#9b8793'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
